# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


ASSEMBLIES = glob_wildcards("data/protein_seq/{assembly}.faa").assembly


# Load helper functions
include: "rules/common.smk"

# Load rules
include: "rules/run_defense_finder.smk"
include: "rules/update_padloc_db.smk"
include: "rules/run_padloc.smk"
include: "rules/systems_by_assembly.smk"
include: "rules/systems_by_assembly_summarised.smk"
include: "rules/systems_all_assemblies.smk"
include: "rules/heatmap.smk"

# Target rule
rule all:
    input: "results/main/heatmap.png"
