# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
# singularity: "docker://continuumio/miniconda3"
containerized: "docker://ezherman/find-defence-systems"

# Load helper functions
include: "rules/common.smk"

# Load rules
include: "rules/obtain_genome_data.smk"
include: "rules/update_defense_finder_models.smk"
include: "rules/run_defense_finder.smk"
include: "rules/update_padloc_db.smk"
include: "rules/run_padloc.smk"
include: "rules/obtain_padloc_locus_tags.smk"
include: "rules/obtain_defense_finder_locus_tags.smk"
include: "rules/filter_padloc_systems.smk"
include: "rules/rename_defense_finder_systems.smk"
include: "rules/rename_padloc_systems.smk"
include: "rules/subsystems_by_sample.smk"
include: "rules/systems_by_sample.smk"
include: "rules/matrix_all_samples.smk"
include: "rules/heatmap.smk"

# Target rule
rule all:
    input:
        heatmap = "results/main/heatmap_systems.png",
        matrix_systems = "results/main/matrix_systems.csv",
        matrix_subsystems = "results/main/matrix_subsystems.csv"
